# Stage 1: Build the Angular application
FROM node:24-alpine AS build
RUN apk update && apk upgrade --no-cache && \
    apk add --no-cache openjdk17-jre openssl

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to install dependencies
COPY package*.json ./

# Install project dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Generate API models
RUN npm run openApi

# Build the Angular application for production
RUN npm run build

# Stage 2: Serve the Angular application with Nginx
FROM nginx:stable-alpine3.23
RUN apk update && apk upgrade --no-cache && \
    apk add --no-cache openssl ca-certificates


# Copy the built Angular application from the 'build' stage to Nginx's default public directory
COPY --from=build /app/dist/beeracademy-frontend/browser /usr/share/nginx/html

# Copy and prepare entrypoint script
COPY docker-entrypoint.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh

# Expose port 80 (Nginx default HTTP port)
EXPOSE 80

# Command to start Nginx
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]
