# Stage 1: Build the Angular application
FROM node:20-alpine AS build

# Install Java (required for openapi-generator-cli)
RUN apk add --no-cache openjdk17-jre

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to install dependencies
COPY package*.json ./

# Install project dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Generate API models
RUN npm run openApi

# Build the Angular application for production
RUN npm run build


# Stage 2: Serve the Angular application with Nginx
FROM nginx:alpine

# Copy the built Angular application from the 'build' stage to Nginx's default public directory
COPY --from=build /app/dist/beeracademy-frontend/browser /usr/share/nginx/html

# Optional: Copy a custom Nginx configuration if you have one
# COPY nginx.conf /etc/nginx/nginx.conf

# Expose port 80 (Nginx default HTTP port)
EXPOSE 80

# Command to start Nginx
CMD ["nginx", "-g", "daemon off;"]
