sonar.projectKey=beeracademy-frontend
sonar.organization=mathias
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.spec.ts,src/testing/**
sonar.exclusions=src/api-models/**,src/**/*.spec.ts,src/testing/**
sonar.coverage.exclusions=src/mocks/**,src/main.ts
sonar.javascript.lcov.reportPaths=coverage/beeracademy-frontend/lcov.info
sonar.testExecutionReportPaths=coverage/sonar-report.xml
